# ref: https://herdr.dev/docs/config-reference/

[theme]
name = "catppuccin"
auto_switch = false

[ui]
show_agent_labels_on_pane_borders = true
#sidebar.spaces.rows = [["state_icon", "workspace"], ["branch", "git_status"]]
#sidebar.spaces.rows = [["state_icon", "workspace"]]
#sidebar.agents.rows = [["state_icon", "workspace", "tab"], ["agent"]]
sidebar.agents.rows = [["state_icon", "workspace", "tab"]]

[keys]
prefix = "ctrl+a"
detach = "prefix+d"

# workspace
next_workspace = ["ctrl+."]
previous_workspace = ["ctrl+,"]
switch_workspace = "prefix+1..9"

# tab
next_tab = ["ctrl+right", "prefix+n"]
previous_tab = ["ctrl+left", "prefix+p"]
rename_tab = "prefix+r"

# pane
cycle_pane_next = "shift+right"
cycle_pane_previous = "shift+left"
split_vertical =  "prefix+|"
zoom = "prefix+m"

# agent
next_agent = ["ctrl+;"]
previous_agent = ["ctrl+'"]

# worktree
remove_worktree = "prefix+shift+d"

[[keys.command]]
key = "prefix+l"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+i"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+a"
type = "plugin_action"
command = "navigate_line.jump_start"
description = "send ctrl+a to pane"

[[keys.command]]
key = "prefix+shift+n"
type = "plugin_action"
command = "navigate_line.create_workspace"
description = "create workspace from directory prompt"

