# /// script
# requires-python = ">=3.11"
# dependencies = ["tomlkit"]
# ///
"""Merge config.toml with override.<machine>.toml into ~/.config/herdr/config.<machine>.toml.

Usage: uv run override_config.py <machine>
Then set HERDR_CONFIG_PATH=~/.config/herdr/config.<machine>.toml on that machine.

Merge rules: tables merge recursively; arrays of tables ([[...]]) append;
scalars and plain arrays are replaced by the override value.
"""
import sys
from pathlib import Path

import tomlkit
from tomlkit.items import AoT

HERDR_DIR = Path(__file__).resolve().parent
CONFIG_DIR = Path.home() / ".config" / "herdr"


def merge_table(base, override):
    for key, value in override.items():
        if key in base and isinstance(base[key], AoT) and isinstance(value, AoT):
            for item in value:
                base[key].append(item)
        elif key in base and isinstance(base[key], dict) and isinstance(value, dict):
            merge_table(base[key], value)
        else:
            base[key] = value


def main():
    if len(sys.argv) != 2:
        sys.exit(f"usage: uv run {Path(sys.argv[0]).name} <machine>")
    machine = sys.argv[1]

    base_path = HERDR_DIR / "config.toml"
    override_path = HERDR_DIR / f"override.{machine}.toml"
    output_path = CONFIG_DIR / f"config.{machine}.toml"

    for path in (base_path, override_path):
        if not path.exists():
            sys.exit(f"error: {path} does not exist")

    doc = tomlkit.parse(base_path.read_text())
    merge_table(doc, tomlkit.parse(override_path.read_text()))

    header = (
        f"# GENERATED by override_config.py from config.toml + {override_path.name}\n"
        "# Do not edit. Edit the sources in the dotfiles repo, then re-run:\n"
        f"#   uv run override_config.py {machine}\n\n"
    )
    output_path.write_text(header + tomlkit.dumps(doc))
    print(f"wrote {output_path}")
    print(f'make sure HERDR_CONFIG_PATH="{output_path}" is set on {machine},')
    print("then run: herdr server reload-config")


if __name__ == "__main__":
    main()
