theme = "catppuccin_mocha"
#client_id = "65b708073fc0480ea92a077233ca87bd"
client_id_command = "echo $SPOTIFYD_CLIENT_ID"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists} {liked}
{album}
{metadata}"""
notify_timeout_in_secs = 0
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
enable_media_control = false
enable_streaming = "Always"
#enable_streaming = "Never"
enable_notify = true
enable_cover_image_cache = true
default_device = "spotifyd"
notify_streaming_only = false
seek_duration_secs = 5
sort_artist_albums_by_type = false

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[layout]
playback_window_position = "Top"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 90
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
